$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_diabetes_model
display_name: Train Diabetes Classification Model

environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

inputs:
  training_data:
    type: uri_folder
  reg_rate:
    type: number

code: ../model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}
