name: Trigger Azure ML jobs

on:
  push:
    branches:
    - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger ML job
      run: |
        az ml job create \
        --file src/job-dev.yml \
        --resource-group learn \
        --workspace-name mlops \
        --stream

  production:
    runs-on: ubuntu-latest
    environment: prod
    needs: experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger ML job
      run: |
        az ml job create \
        --file src/job-prod.yml \
        --resource-group learn \
        --workspace-name mlops \
        --stream