name: Deploy and test model

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set up azure-cli
      run: |
        az extension add -n ml -y
        az configure --defaults workspace=mlops group=learn
    - name: Create endpoint
      run: az ml online-endpoint create --file src/endpoint.yml
      continue-on-error: true
    - name: Deploy model
      run: az ml online-deployment create --file src/deployment.yml --all-traffic
    - name: Test model
      run: az ml online-endpoint invoke --name mlops-diabetes --request-file experimentation/sample-request.json 
